# Generated by Django 5.0.1 on 2024-01-13 14:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Game",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=150, verbose_name="название")),
                ("size", models.PositiveSmallIntegerField(verbose_name="размер")),
                ("text", models.TextField(verbose_name="описание")),
                (
                    "status",
                    models.IntegerField(
                        choices=[(1, "Не начата"), (2, "Начата"), (3, "Окончена")],
                        verbose_name="статус",
                    ),
                ),
                (
                    "link",
                    models.CharField(
                        blank=True, max_length=10, null=True, verbose_name="ссылка"
                    ),
                ),
                (
                    "finish_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="игра завершена"
                    ),
                ),
                (
                    "users",
                    models.ManyToManyField(
                        related_name="game", to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
            options={
                "verbose_name": "Игра",
                "verbose_name_plural": "Игры",
            },
        ),
        migrations.CreateModel(
            name="Cell",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("y", models.PositiveSmallIntegerField()),
                ("x", models.PositiveSmallIntegerField()),
                (
                    "status",
                    models.IntegerField(
                        choices=[
                            (1, "Пустая"),
                            (2, "Уничтоженная"),
                            (3, "Стоит корабль"),
                            (4, "Стоит уничтоженный корабль"),
                        ],
                        verbose_name="статус",
                    ),
                ),
                (
                    "shot_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cell",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="уничтожена игроком",
                    ),
                ),
                (
                    "game",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cell",
                        to="game.game",
                        verbose_name="игра",
                    ),
                ),
            ],
            options={
                "verbose_name": "Клетка",
                "verbose_name_plural": "Клетки",
            },
        ),
        migrations.CreateModel(
            name="Prize",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=150, verbose_name="название")),
                ("text", models.TextField(verbose_name="описание")),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="prize_images/",
                        verbose_name="картинка приза",
                    ),
                ),
                (
                    "activation_code",
                    models.CharField(
                        blank=True,
                        max_length=10,
                        null=True,
                        verbose_name="код активации",
                    ),
                ),
                (
                    "winner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="prize",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="победитель",
                    ),
                ),
            ],
            options={
                "verbose_name": "Приз",
                "verbose_name_plural": "Призы",
            },
        ),
        migrations.CreateModel(
            name="Ship",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_alive", models.BooleanField(default=True, verbose_name="жив")),
                (
                    "cell",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ship",
                        to="game.cell",
                        verbose_name="клетка",
                    ),
                ),
                (
                    "game",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ship",
                        to="game.game",
                        verbose_name="игра",
                    ),
                ),
                (
                    "prize",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ship",
                        to="game.prize",
                        verbose_name="приз",
                    ),
                ),
            ],
            options={
                "verbose_name": "Корбаль",
                "verbose_name_plural": "Корабли",
            },
        ),
        migrations.CreateModel(
            name="UserShots",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "game",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_shots",
                        to="game.game",
                        verbose_name="игра",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_shots",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Выстрелы пользователей",
            },
        ),
    ]
