# Generated by Django 5.0.1 on 2024-01-12 16:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("game", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="prize",
            name="activation_code",
            field=models.CharField(
                default="qwerty", max_length=150, verbose_name="код активации"
            ),
            preserve_default=False,
        ),
    ]
