# Generated by Django 5.0.1 on 2024-01-14 16:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("game", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="usershots",
            name="count",
            field=models.IntegerField(default=2, verbose_name="количество выстрелов"),
        ),
    ]
