# Generated by Django 5.0.1 on 2024-01-12 17:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("game", "0002_prize_activation_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="prize",
            name="activation_code",
            field=models.CharField(
                blank=True, max_length=150, null=True, verbose_name="код активации"
            ),
        ),
        migrations.AlterField(
            model_name="prize",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="prize_images/",
                verbose_name="картинка приза",
            ),
        ),
    ]
