# Generated by Django 5.0.1 on 2024-01-14 18:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("game", "0003_alter_prize_activation_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="prize",
            name="game",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="prize",
                to="game.game",
                verbose_name="игра",
            ),
            preserve_default=False,
        ),
    ]
