# Generated by Django 5.0.1 on 2024-01-12 17:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("game", "0003_alter_prize_activation_code_alter_prize_image"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="cell",
            options={"verbose_name": "Клетка", "verbose_name_plural": "Клетки"},
        ),
        migrations.AlterModelOptions(
            name="game",
            options={"verbose_name": "Игра", "verbose_name_plural": "Игры"},
        ),
        migrations.AlterModelOptions(
            name="prize",
            options={"verbose_name": "Приз", "verbose_name_plural": "Призы"},
        ),
        migrations.AlterModelOptions(
            name="ship",
            options={"verbose_name": "Корбаль", "verbose_name_plural": "Корабли"},
        ),
        migrations.AddField(
            model_name="game",
            name="link",
            field=models.CharField(
                blank=True, max_length=10, null=True, verbose_name="ссылка"
            ),
        ),
        migrations.AlterField(
            model_name="prize",
            name="activation_code",
            field=models.CharField(
                blank=True, max_length=10, null=True, verbose_name="код активации"
            ),
        ),
    ]
