# Generated by Django 5.0.1 on 2024-01-18 21:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("game", "0004_prize_game"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="prize",
            name="image",
        ),
        migrations.AlterField(
            model_name="game",
            name="status",
            field=models.IntegerField(
                choices=[(1, "Не начата"), (2, "Начата"), (3, "Окончена")],
                default=1,
                verbose_name="статус",
            ),
        ),
    ]
