# Generated by Django 5.0.1 on 2024-01-23 21:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("game", "0006_alter_cell_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cell",
            name="status",
            field=models.IntegerField(
                choices=[
                    (0, "Пустая"),
                    (1, "Уничтоженная"),
                    (2, "Стоит корабль"),
                    (3, "Стоит уничтоженный корабль"),
                ],
                default=1,
                verbose_name="статус",
            ),
        ),
        migrations.AlterField(
            model_name="game",
            name="status",
            field=models.IntegerField(
                choices=[
                    (0, "Не опубликована"),
                    (1, "Не начата"),
                    (2, "Начата"),
                    (3, "Окончена"),
                ],
                default=1,
                verbose_name="статус",
            ),
        ),
    ]
