# Generated by Django 5.0.1 on 2024-01-25 20:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("game", "0007_alter_cell_status_alter_game_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="cell",
            name="position",
            field=models.CharField(default="A0", max_length=25, verbose_name="позиция"),
            preserve_default=False,
        ),
    ]
