# Generated by Django 5.0.1 on 2024-01-25 20:17

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("game", "0008_cell_position"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cell",
            name="x",
        ),
        migrations.RemoveField(
            model_name="cell",
            name="y",
        ),
    ]
