# Generated by Django 5.0.1 on 2024-01-27 08:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("game", "0009_remove_cell_x_remove_cell_y"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ship",
            name="cell",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ship",
                to="game.cell",
                verbose_name="клетка",
            ),
        ),
        migrations.AlterField(
            model_name="ship",
            name="prize",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ship",
                to="game.prize",
                verbose_name="приз",
            ),
        ),
    ]
