# Generated by Django 5.0.1 on 2024-01-27 08:49

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("game", "0010_alter_ship_cell_alter_ship_prize"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="usershots",
            unique_together={("user", "game")},
        ),
    ]
