# Generated by Django 5.0.1 on 2024-01-27 11:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("game", "0012_alter_usershots_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cell",
            name="position",
            field=models.CharField(max_length=25, unique=True, verbose_name="позиция"),
        ),
    ]
