# Generated by Django 5.0.1 on 2024-01-27 12:59

import game.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("game", "0013_alter_cell_position"),
    ]

    operations = [
        migrations.AddField(
            model_name="prize",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=game.models.Prize.prize_imgae_upload_to,
                verbose_name="изображение приза",
            ),
        ),
        migrations.AlterField(
            model_name="cell",
            name="status",
            field=models.IntegerField(
                choices=[
                    (0, "Пустая"),
                    (1, "Уничтоженная"),
                    (2, "Стоит корабль"),
                    (3, "Стоит уничтоженный корабль"),
                ],
                default=0,
                verbose_name="статус",
            ),
        ),
    ]
