# Generated by Django 5.0.1 on 2024-02-03 15:51

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("game", "0014_prize_image_alter_cell_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cell",
            name="position",
            field=models.CharField(max_length=25, verbose_name="позиция"),
        ),
        migrations.AlterField(
            model_name="game",
            name="status",
            field=models.IntegerField(
                choices=[
                    (0, "Не опубликована"),
                    (1, "Не начата"),
                    (2, "Начата"),
                    (3, "Окончена"),
                ],
                default=0,
                verbose_name="статус",
            ),
        ),
        migrations.AlterField(
            model_name="game",
            name="text",
            field=ckeditor.fields.RichTextField(verbose_name="текст"),
        ),
        migrations.AlterField(
            model_name="prize",
            name="activation_code",
            field=models.CharField(max_length=150, verbose_name="код активации"),
        ),
        migrations.AlterUniqueTogether(
            name="cell",
            unique_together={("game", "position")},
        ),
    ]
