# Generated by Django 5.0.1 on 2024-01-12 17:41

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="usershots",
            options={"verbose_name_plural": "Выстрелы пользователей"},
        ),
    ]
